import { useState } from 'react';
import { KeyRound, LoaderCircle } from 'lucide-react';

interface ChangePasswordPageProps { fullName: string; onChange: (current: string, next: string, confirmation: string) => Promise<void>; }

// Memaksa pengguna mengganti password awal sebelum mengakses fitur aplikasi.
export function ChangePasswordPage({ fullName, onChange }: ChangePasswordPageProps) {
  const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-4"><form className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl" onSubmit={(event) => { event.preventDefault(); setLoading(true); setError(null); void onChange(current, next, confirmation).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Password gagal diubah.')).finally(() => setLoading(false)); }}><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-100 text-amber-700"><KeyRound className="h-6 w-6"/></span><h1 className="mt-5 text-xl font-bold text-slate-900">Ganti password awal</h1><p className="mt-1 text-sm text-slate-500">Halo {fullName}, buat password pribadi sebelum melanjutkan.</p>{error && <div role="alert" className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</div>}<div className="mt-6 space-y-4"><label className="block text-xs font-bold">Password saat ini<input required type="password" autoComplete="current-password" value={current} onChange={(event) => setCurrent(event.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="block text-xs font-bold">Password baru<input required minLength={8} type="password" autoComplete="new-password" value={next} onChange={(event) => setNext(event.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="block text-xs font-bold">Konfirmasi password baru<input required minLength={8} type="password" autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{loading && <LoaderCircle className="h-4 w-4 animate-spin"/>}Simpan dan login kembali</button></div></form></main>;
}
