import { useRef, useState } from 'react';
import { CheckCircle2, FileSpreadsheet, Info, ShieldCheck, UploadCloud, X } from 'lucide-react';

// Menyediakan simulasi pemilihan file dan preview awal tanpa mengunggah data ke server.
export function ImportPanel() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [fileName, setFileName] = useState('');
  return <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-indigo-50 p-3 text-indigo-600"><UploadCloud className="h-5 w-5" /></span><div><h2 className="text-base font-bold text-slate-900">Upload Data Sumber</h2><p className="text-xs text-slate-400">Pilih workbook transaksi atau tiket aduan</p></div></div><input ref={inputRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? '')}/><button onClick={() => inputRef.current?.click()} className="mt-6 flex min-h-64 w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/70 px-5 transition hover:border-indigo-300 hover:bg-indigo-50/40"><span className="rounded-full bg-white p-4 text-indigo-600 shadow-sm"><FileSpreadsheet className="h-7 w-7" /></span><p className="mt-4 text-sm font-bold text-slate-800">Klik untuk memilih file Excel</p><p className="mt-1 text-xs text-slate-400">XLSX atau XLS, maksimal 25 MB</p></button>{fileName && <div className="mt-4 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-emerald-800">{fileName}</p><p className="text-[10px] text-emerald-600">Siap untuk divalidasi setelah backend tersedia</p></div><button onClick={() => setFileName('')} className="text-emerald-600"><X className="h-4 w-4"/></button></div>}</section><aside className="space-y-5"><div className="rounded-2xl bg-slate-950 p-6 text-white"><ShieldCheck className="h-7 w-7 text-emerald-400"/><h3 className="mt-4 text-sm font-bold">Import Aman & Teraudit</h3><p className="mt-2 text-xs leading-5 text-slate-400">Setiap file akan divalidasi dan dipreview sebelum disimpan. Hash file dan sumber baris dicatat untuk mencegah duplikasi.</p><div className="mt-5 space-y-3 text-xs">{['Validasi header dan format', 'Deteksi periode dari isi data', 'Preview valid, duplikat, invalid', 'Simpan dalam satu transaksi database'].map((text, index) => <div key={text} className="flex items-center gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-white/10 text-[10px] font-bold text-indigo-300">{index + 1}</span><span className="text-slate-300">{text}</span></div>)}</div></div><div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><Info className="h-5 w-5 shrink-0 text-amber-600"/><p className="text-xs leading-5 text-amber-800">File belum dikirim ke mana pun. Halaman ini masih berupa prototipe UI lokal.</p></div></aside></div>;
}
