import { useState } from 'react';
import { LoaderCircle, LockKeyhole, WalletCards } from 'lucide-react';

interface LoginPageProps { onLogin: (login: string, password: string) => Promise<void>; }

// Menampilkan form login terisolasi sebelum dashboard dan datanya dirender.
export function LoginPage({ onLogin }: LoginPageProps) {
  const [login, setLogin] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-4"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white p-7 shadow-2xl"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600 text-white"><WalletCards className="h-6 w-6"/></span><h1 className="mt-5 text-xl font-bold text-slate-900">Merchant Performance</h1><p className="mt-1 text-sm text-slate-500">Masuk menggunakan akun yang diberikan administrator.</p>{error && <div role="alert" className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</div>}<form className="mt-6 space-y-4" onSubmit={(event) => { event.preventDefault(); setLoading(true); setError(null); void onLogin(login, password).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Login gagal.')).finally(() => setLoading(false)); }}><label className="block text-xs font-bold text-slate-700">Username atau email<input required autoFocus autoComplete="username" value={login} onChange={(event) => setLogin(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm outline-none focus:border-indigo-500"/></label><label className="block text-xs font-bold text-slate-700">Password<input required type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm outline-none focus:border-indigo-500"/></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{loading ? <LoaderCircle className="h-4 w-4 animate-spin"/> : <LockKeyhole className="h-4 w-4"/>}{loading ? 'Memverifikasi...' : 'Masuk'}</button></form></div></main>;
}
