import { useEffect, useState } from 'react';
import { KeyRound, LoaderCircle, Pencil, Plus, UsersRound, X } from 'lucide-react';
import { createUser, fetchRoles, fetchUsers, resetUserPassword, updateUser, type ManagedUser, type RoleOption } from '../services/userApi';
import type { UserRole } from '../services/authApi';

interface Props { open: boolean; onClose: () => void; }
type UserForm = { public_id?: string; username: string; full_name: string; email: string; role: UserRole; is_active: boolean; password: string; confirmation: string; };
const emptyForm: UserForm = { username: '', full_name: '', email: '', role: 'viewer', is_active: true, password: '', confirmation: '' };

// Menyediakan seluruh pengelolaan akun yang hanya dibuka untuk Super Admin.
export function UserManagementModal({ open, onClose }: Props) {
  const [users, setUsers] = useState<ManagedUser[]>([]); const [roles, setRoles] = useState<RoleOption[]>([]); const [form, setForm] = useState<UserForm | null>(null); const [resetTarget, setResetTarget] = useState<ManagedUser | null>(null); const [resetPassword, setResetPassword] = useState(''); const [resetConfirmation, setResetConfirmation] = useState(''); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);

  // Memuat user dan role bersama-sama setiap modal dibuka atau data berubah.
  async function load(): Promise<void> { setLoading(true); setError(null); try { const [userRows, roleRows] = await Promise.all([fetchUsers(), fetchRoles()]); setUsers(userRows); setRoles(roleRows); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Data pengguna gagal dimuat.'); } finally { setLoading(false); } }
  useEffect(() => { if (open) void load(); }, [open]);

  // Menyimpan akun baru atau perubahan akun yang dipilih.
  async function save(): Promise<void> { if (!form) return; setSaving(true); setError(null); try { if (form.public_id) await updateUser({ public_id: form.public_id, full_name: form.full_name, email: form.email, role: form.role, is_active: form.is_active }); else await createUser({ username: form.username, full_name: form.full_name, email: form.email, role: form.role, password: form.password, password_confirmation: form.confirmation }); setForm(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Pengguna gagal disimpan.'); } finally { setSaving(false); } }

  // Menyimpan password sementara baru untuk target yang dipilih.
  async function applyReset(): Promise<void> { if (!resetTarget) return; setSaving(true); setError(null); try { await resetUserPassword(resetTarget.public_id, resetPassword, resetConfirmation); setResetTarget(null); setResetPassword(''); setResetConfirmation(''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Password gagal direset.'); } finally { setSaving(false); } }

  if (!open) return null;
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/50 p-4"><section className="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-5"><div className="flex items-center gap-3"><UsersRound className="h-5 w-5 text-indigo-600"/><div><h2 className="font-bold">Manajemen Pengguna</h2><p className="text-xs text-slate-500">Kelola akun, role, status, dan password sementara.</p></div></div><div className="flex gap-2"><button onClick={() => setForm({ ...emptyForm })} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Tambah</button><button onClick={onClose}><X className="h-5 w-5"/></button></div></header>{error && <div className="m-4 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}<div className="overflow-auto">{loading ? <div className="flex min-h-64 items-center justify-center text-sm text-slate-500"><LoaderCircle className="mr-2 h-4 w-4 animate-spin"/>Memuat pengguna...</div> : <table className="w-full min-w-[800px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="p-4">Pengguna</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Login terakhir</th><th className="p-4">Aksi</th></tr></thead><tbody className="divide-y">{users.map((item) => <tr key={item.public_id}><td className="p-4"><strong>{item.full_name}</strong><p className="text-slate-400">@{item.username}{item.email ? ` · ${item.email}` : ''}</p></td><td className="p-4 font-semibold">{item.role_name}</td><td className="p-4">{Number(item.is_active) === 1 ? 'Aktif' : 'Nonaktif'}{Number(item.must_change_password) === 1 && <span className="ml-2 rounded bg-amber-100 px-2 py-1 text-[9px] text-amber-700">Wajib ganti password</span>}</td><td className="p-4 text-slate-500">{item.last_login_at ?? 'Belum pernah'}</td><td className="p-4"><div className="flex gap-1"><button title="Edit" onClick={() => setForm({ public_id: item.public_id, username: item.username, full_name: item.full_name, email: item.email ?? '', role: item.role, is_active: Number(item.is_active) === 1, password: '', confirmation: '' })} className="rounded-lg border p-2"><Pencil className="h-4 w-4"/></button><button title="Reset password" onClick={() => setResetTarget(item)} className="rounded-lg border p-2"><KeyRound className="h-4 w-4"/></button></div></td></tr>)}</tbody></table>}</div></section>
    {form && <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); void save(); }} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h3 className="font-bold">{form.public_id ? 'Edit Pengguna' : 'Tambah Pengguna'}</h3><button type="button" onClick={() => setForm(null)}><X className="h-4 w-4"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{!form.public_id && <label className="text-xs font-bold">Username<input required value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} className="mt-1 w-full rounded-xl border p-2.5"/></label>}<label className="text-xs font-bold">Nama lengkap<input required value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} className="mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold">Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold">Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as UserRole })} className="mt-1 w-full rounded-xl border p-2.5">{roles.map((role) => <option key={role.code} value={role.code}>{role.name}</option>)}</select></label>{form.public_id ? <label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })}/>Akun aktif</label> : <><label className="text-xs font-bold">Password sementara<input required minLength={8} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold">Konfirmasi<input required minLength={8} type="password" value={form.confirmation} onChange={(e) => setForm({ ...form, confirmation: e.target.value })} className="mt-1 w-full rounded-xl border p-2.5"/></label></>}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setForm(null)} className="rounded-xl border px-4 py-2">Batal</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-4 py-2 text-white">Simpan</button></div></form></div>}
    {resetTarget && <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={(e) => { e.preventDefault(); void applyReset(); }} className="w-full max-w-md rounded-2xl bg-white p-5"><h3 className="font-bold">Reset password {resetTarget.full_name}</h3><input required minLength={8} type="password" placeholder="Password sementara" value={resetPassword} onChange={(e) => setResetPassword(e.target.value)} className="mt-4 w-full rounded-xl border p-3"/><input required minLength={8} type="password" placeholder="Konfirmasi password" value={resetConfirmation} onChange={(e) => setResetConfirmation(e.target.value)} className="mt-3 w-full rounded-xl border p-3"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setResetTarget(null)} className="rounded-xl border px-4 py-2">Batal</button><button disabled={saving} className="rounded-xl bg-amber-600 px-4 py-2 text-white">Reset</button></div></form></div>}
  </div>;
}
